---

- debug:
    msg: " ---- Configurar bonding ----"

- name: "Instalando paquetes necesarios " 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ifenslave


- name: "add bonding in /etc/modules"
  become: yes
  lineinfile:
    path: /etc/modules
    state: present
    line: 'bonding'

- name: Add the bonding module
  become: yes
  modprobe:
    name: bonding
    state: present

- name: configure link aggregation group
  become: yes
  net_linkagg:
    name: bond0
    members:
      - eth0
      - wlan0
